server:
  port: 80

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/test
    username: test
    password: test@dba
    driver-class-name: org.postgresql.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-wait: 60000
